site_name: Halping Hand
site_author: Crownest
copyright: Crownest
theme:
    name: mkdocs
    custom_dir: docs_theme
site_dir: docs_build
use_directory_urls: false

pages:
    - Home: index.md
    - Backend:
      - Development: backend/development.md
