# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Is Fixed')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_needs', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('supporters', models.ManyToManyField(related_name='supporter_needs', to=settings.AUTH_USER_MODEL, verbose_name='Supporters')),
            ],
            options={
                'verbose_name': 'Need',
                'verbose_name_plural': 'Needs',
            },
        ),
    ]
