# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('needs', '0002_auto_20180522_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='needs', to='categories.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='needitem',
            name='remaining',
            field=models.CharField(blank=True, max_length=254, verbose_name='Remaining'),
        ),
        migrations.AlterField(
            model_name='need',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supporter_needs', to=settings.AUTH_USER_MODEL, verbose_name='Supporters'),
        ),
    ]
